-- Ejecutar en Supabase SQL Editor para habilitar las reseñas públicas.
create table if not exists public.customer_reviews (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 2 and 60),
  rating smallint not null check (rating between 1 and 5),
  comment text not null check (char_length(comment) between 8 and 1200),
  image_url text not null,
  florist_reply text check (florist_reply is null or char_length(florist_reply) <= 1200),
  created_at timestamptz not null default now()
);

alter table public.customer_reviews enable row level security;
grant select, insert on public.customer_reviews to anon, authenticated;
grant update (florist_reply) on public.customer_reviews to authenticated;
grant usage, select on sequence public.customer_reviews_id_seq to anon, authenticated;

create policy "Public can read customer reviews"
  on public.customer_reviews for select to anon, authenticated
  using (true);

create policy "Visitors can submit customer reviews"
  on public.customer_reviews for insert to anon, authenticated
  with check (
    char_length(name) between 2 and 60
    and rating between 1 and 5
    and char_length(comment) between 8 and 1200
    and image_url like '%/storage/v1/object/public/ramilletes-clientes/%'
  );

create policy "Florist can reply to reviews"
  on public.customer_reviews for update to authenticated
  using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'floristeria')
  with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'floristeria');

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('ramilletes-clientes', 'ramilletes-clientes', true, 5242880, array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "Public can view customer bouquet photos"
  on storage.objects for select to anon, authenticated
  using (bucket_id = 'ramilletes-clientes');

create policy "Visitors can upload customer bouquet photos"
  on storage.objects for insert to anon, authenticated
  with check (bucket_id = 'ramilletes-clientes');
